### ISSUE TITLE
Fill not updating in Framer.

### ISSUE THREAD

**Issue by artsvuni** [iKettles/framer-svg-component-generator#1]
Hi. Your generator is great! Was lucky to find it. 

I've generated group of SVG's from sketch. 
But after using your generator — I can see all the icons in Framer X  But somehow PropertyControl in Framer does not change the fill colour of icons.

It seems that icons generated all have `fill="#222222"` replacing this with `fill={props.fill}` fixes it. 
So my question is — is something going wrong during icon generation?

**Comment by iKettles** [comment]
@artsvuni glad you like it and thanks for making this issue!

The `{...props}` in the end of the outer SVG tag overrides any former props, so even if the fill attribute is hardcoded the fill from the property controls should take precedent, but that won't apply to child elements that also declare their own fill. I'd hesitated from implementing this for the first version as it completely overrides the color of any child element and prevents you from having multiple colors within a single SVG, although I think that's an edge case.

This has been fixed in #2, will publish a new version shortly!

**Comment by farfetch-design** [comment]
@iKettles  thanks 🙌
